### ISSUE TITLE
Amount of hashtags?

### ISSUE THREAD

**Issue by quintendewilde** [simonseo/instagram-hashtag-crawler#5]
Hi I would like to get the amount of hashtags of a certain target? Is that possible?

I'm not the best python coder so any help would be very appriciated....

**Comment by nokey-54** [comment]
Do it like
// read the file
`var fileContent = JSON.parse(filePathToHashtagCrawlerJson)
fileContent.posts.forEach(async (p) => {
					var val = await new Promise( (resolve) => {
						if (Array.isArray(p.tags)) {
							p.tags.forEach(async (t) => {
								var v = t.toLowerCase().substring(1);
								if (v.match("//^#\w+$")) {
									resolve(v);
								}
							});
						}
					});
					if (val) {
console.log("hashtag: " + val " valid");
					}
				});`
